### ISSUE TITLE
FYI: node-sass version needs updated to work with Node 13.x

### ISSUE THREAD

**Issue by sc0ttwad3** [gk4m/vue-spotify#12]
Great project and example that's very much appreciated!

FYI: Users running node 13.x need to update the dev-dependency on node-sass@4.12.0 to node-sass@4.13.0, or the initial ```npm install``` fails. (can attach debug-log files if requested). 

Manually changing the package.json file specified version, then retrying ```npm install```, then proceeds successfully. 

[_I'd send a pull request if this was more than a one file/one number modification_] 

![node-sass-versions](https://user-images.githubusercontent.com/1682691/70380831-4d482900-190f-11ea-802b-3adc06dedb90.jpg)

**Comment by gk4m** [comment]
@sc0ttwad3 If you want you can create PR for it. If not I will do this later.

**Comment by gk4m** [comment]
I updated `node-sass` to newest version. So now it should works with node 13.
