### ISSUE TITLE
Api on port 4040

### ISSUE THREAD

**Issue by narimantos** [gk4m/vue-spotify#15]
https://github.com/gk4m/vue-spotify/blob/bc0e5ee86ea823fec31d910e0d47b9867399f81f/src/api/auth/request.js#L8

do you have an example on what runs behind 4040?

**Comment by gk4m** [comment]
@narimantos Here you have repository https://github.com/gk4m/spotify-auth-api

**Comment by narimantos** [comment]
ah great thanks!
